### ISSUE TITLE
Z-side #023

### ISSUE THREAD

**Issue by rbtnn** [drikin/backspace#451]
* [mstdn-pickerによるグルドン過去ログ(Z-side#023)](https://rbtnn.github.io/mstdn-picker/?instance=mstdn.guru&since_id=100100243431182016&max_id=100100708722418914)

**Comment by Okitaka** [comment]
* [Detroit: Become Human | Revisiting Kara | PS4 - YouTube](https://www.youtube.com/watch?v=RdEjAkvwCzU&feature=youtu.be)
* [映画『エクス・マキナ』予告編 - YouTube](https://www.youtube.com/watch?v=D9UOrMgCfSs&feature=youtu.be)
* [Brainstorm (1983) [Trailer] - YouTube](https://www.youtube.com/watch?v=NNiZP2G-nEM&feature=youtu.be)

**Comment by Okitaka** [comment]
* [cluster.](https://cluster.mu/)
* [VRWorks - 360 Video | NVIDIA Developer](https://developer.nvidia.com/vrworks/vrworks-360video)
* [『楽園追放 -Expelled from Paradise-』](http://rakuen-tsuiho.com/)
* [Professional VR Camera & Software Company | Z CAM](http://www.z-cam.com/)
