### ISSUE TITLE
z-side #027

### ISSUE THREAD

**Issue by rbtnn** [drikin/backspace#611]

**Comment by drikin** [comment]
[西川善司 - 4Gamer.net](https://www.4gamer.net/words/000/W00064/)
[西川善司の3DGE：Zen 2×PCIe4時代のAM4プラットフォームアップグレード指南～PCIe4の直接の恩恵はグラフィックスよりもストレージのパフォーマンス？ - 4Gamer.net](https://www.4gamer.net/games/446/G044684/20190531162/)
[「Ryzen 9 3950X」は16コア32スレッドに到達。AMDが独自イベントで「Ryzen 3000」の追加ラインナップを発表 - 4Gamer.net](https://www.4gamer.net/games/446/G044684/20190610131/)
[西川善司の3DGE：次世代GPU「Navi」の詳細とRadeon Softwareの新機能をレポート。操作遅延を低減する「Anti-Lag」は本当に効くのか？ - 4Gamer.net](https://www.4gamer.net/games/337/G033715/20190612140/)
[西川善司の3DGE：次世代GPU「Radeon RX 5700」シリーズの秘密に迫る。レイトレーシング対応は第2世代Naviに持ち越し？ - 4Gamer.net](https://www.4gamer.net/games/337/G033715/20190610139/)
[西川善司の3DGE：赤と緑のケンカ再び。NVIDIAが「Navi」の特徴や「Radeon Software」の新機能に反論する - 4Gamer.net](https://www.4gamer.net/games/337/G033715/20190614139/)
[Mac Pro - Apple](https://www.apple.com/mac-pro/)
[西川善司の3DGE：COMPUTEX 2019 NVIDIAプレスカンファレンスで発表された不思議なブランディングキーワード「NVIDIA Studio」と「RTX Studio」ってなに？ - 4Gamer.net](https://www.4gamer.net/games/421/G042134/20190528113/)
[MAC vs PC IN 2019 - YouTube](https://www.youtube.com/watch?v=NRm0hn2RRvE&t=0s)
[Amazon.com: MSI P65 Creator-654 15.6" Productivity Laptop, 4K Display, Ultra Portable, Thin Bezel, Intel Core i9-9880H, NVIDIA GeForce RTX2070, 32GB, 1TB NVMe SSD, Thunderbolt 3: Computers & Accessories](https://www.amazon.com/gp/product/B07QP4Y176/ref=as_li_tl?ie=UTF8&tag=trave0063-20&camp=1789&creative=9325&linkCode=as2&creativeASIN=B07QP4Y176&linkId=2cdd4c2b0805acbd68b792cee23616f0)
[新型モバイルディスプレイからプロユースの「Mini LED×量子ドット」製品まで，COMPUTEXで見た変わり種液晶ディスプレイ総ざらえ - 4Gamer.net](https://www.4gamer.net/games/047/G004755/20190607002/)
[Gigabyte's Aero 15 OLED laptop is made for video editors (updated)](https://www.engadget.com/2019/05/28/gigabyte-aero-15-oled-4k-hands-on/?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvLmpwLw&guce_referrer_sig=AQAAACzLi4GpdzntL-8XAoRzBDu9gVWYww7tGvHBpYna_ihmum8XvlcyuDHMx_s6DwfStEhLeZqxG5avNdE12R8aTbkp8zZcgaLWcvuIdJBKM6J2yX0huD9dWtl8eI2X0-olffs_VqtabdnmGui74XfNP3T2ahMbiXjCw7mJSFCxNJTF)

**Comment by Okitaka** [comment]
[z027 - OneDrive](https://1drv.ms/u/s!AuqR4ORN1fzLg8ZA7ohhPPNye3raJA?e=12SZXy)

**Comment by mazzo-p** [comment]
絶好調AMDの今、自作PCをどう構成すべきか

最近絶好調と噂のAMDを軸に、どう自作PCを構成すべきなのか、カンファレンスにも出た西川善司さんに最新情報をアドバイスしてもらった。
