### ISSUE TITLE
backspace.fm B-side #002

### ISSUE THREAD

**Issue by mazzo-p** [drikin/backspace#77]
# 今日のネタ

- 雰囲気メガネdrikin分
- netatomo買った
- vaioz vs dell xps 13
- pushbulletでFBMリプライ可能に
- google plusのフォト編集機能 Snapseed
- 最近のコメント紹介
- ITmedia News読者感謝祭、いよいよ

# 先週のbackspace振り返り
- guilty gear試した

# 今週のbackspace予告
- niw先生

**Comment by drikin** [comment]
最近のコメント紹介

**Comment by drikin** [comment]
vaioz vs dell xps 13

**Comment by drikin** [comment]
pushbulletでFBMリプライ可能に

**Comment by drikin** [comment]
netatomo買った

**Comment by drikin** [comment]
google　plusのフォト編集機能

**Comment by mazzo-p** [comment]
ITmedia News読者感謝祭、いよいよ
