### ISSUE TITLE
元VAIOソフトウェアエンジニア野間さんと語るPCの現在と未来と非モテw

### ISSUE THREAD

**Issue by drikin** [drikin/backspace#79]
今週の公開生放送は日本時間2月22日(日曜)午後2時頃からの収録を予定しています。生放送の閲覧は下記のURLからご覧頂けます。

http://backspace.fm/live.html
# ごあいさつ

こんにちは、backspace.fm 第85回です。
backspace.fmは一週間分のテック系ニュースをお届けするPodcastです。
## 今週の一言

@mazzo: 

@drikin:

@kai4den:
## 今回のbackspace.fmについて

(mazzo) 今回のbackspace.fmは、元VAIOソフトウェアエンジニアで、現在は非モテサバイバル本部長として活躍されているのまのしわざの野間さんをゲストにお迎えして、現状のPCとその未来、更には非モテについて語って頂きたいと思っています。

(mazzo) では、野間さん、簡単に自己紹介をお願いします！

<ここで野間さん自己紹介>
## 番組フィードバックと配信スケジュールについて

(drikin) 番組に対するフィードバックは#backspacefmにてお願いします！ http://backspace.fm/live.html から視聴頂くと、ページ内のTwitterリストからハッシュタグ付きツイートが簡単にできます！番組中のリアルタイムフィードバックもお待ちしていますのでフィードバックよろしくお願いします。

また生放送スケジュールはGoogleカレンダーにて日程を公開しています。生放送を聞きたい方はぜひカレンダーを登録してください。

https://www.google.com/calendar/embed?src=je3ul6a9tp9esq6efrouf1ht6c%40group.calendar.google.com&ctz=Japan/Tokyo
# 今週のスペシャル (60分)
### 質問集
- 改めて野間さんの自己紹介
  - [Tiny AIBO Ver.3.0](http://www.sony.jp/ProductsPark/Consumer/PCOM/Software_01q2/TinyAIBO/)
  - [ワンダードライビング／乗り物とホビーのブログメディア](http://wonderdriving.com/)
- 野間さんの最近の主な活動は？
- 最近発売されたVaioZやVAIO株式会社について
- そもそもPCの今、未来
- iPhone/Android/iPadについては？
- ワンドラトーク
  - 若者の車離れ
- 非モテトーク
  - どういう経緯で始めた？
  - 野間さんのポジションは？
- 野間さんの予測する2015年の動向は？
### 関連リンク
- [予想以上にNDロードスターがS2000な件 - のまのしわざ](http://nomano.shiwaza.com/tnoma/blog/archives/009005.html)
- [【まとめ】マイカー vs カーシェア・レンタカーではなく、多様性と選択の自由を - のまのしわざ](http://nomano.shiwaza.com/tnoma/blog/archives/008992.html)
- [Dyson AM10 加湿器で完全無欠のうるおいを #dysonjp - のまのしわざ](http://nomano.shiwaza.com/tnoma/blog/archives/008995.html)
- [子供を昭和で育てる - のまのしわざ](http://nomano.shiwaza.com/tnoma/blog/archives/008983.html)
- [非モテサバイバル](http://himotesurvival.hatenablog.com/)
- [ワンダードライビング／乗り物とホビーのブログメディア](http://wonderdriving.com/)
# 今週のニュース (30分)
1. [【イベントレポート】ITmedia読者感謝祭の参加レポートまとめ。当日聴いた話、会場の雰囲気など | そうすけブログ.com](http://sosukeblog.com/2015/02/22/8765/)
2. [Google Inbox now works on tablets and more browsers](http://www.neowin.net/news/google-inbox-now-works-on-tablets-and-more-browsers)
3. [Apple Said To Be Planning OS X-Like Public Beta Seed Program For iOS, Too | TechCrunch](http://techcrunch.com/2015/02/20/apple-said-to-be-planning-os-x-like-public-beta-seed-program-for-ios-too/)
4. [サウンドも「Photoshop」する時代 : ギズモード・ジャパン](http://www.gizmodo.jp/2015/02/photoshop_30.html)
5. [米国のテレビ局が密かに映画やドラマを加速圧縮再生、CM時間を水増し (動画) 1. Engadget Japanese](http://japanese.engadget.com/2015/02/20/speed-up-shows/?ncid=rss_truncated)
6. [もう、ささらだけではない――「調教いらず」のCeVIOに“新人”歌手がJOYSOUNDから　おっさん・熟女の「演歌歌手」も 1. ITmedia ニュース](http://www.itmedia.co.jp/news/articles/1502/19/news133.html)
7. [【必見】NTTドコモ「ｄマガジン」をパソコン（PC）で読む方法！ | IT大好き！](http://itdaisuki.com/app/1487/)
# 今週のガジェット (30分)
1. [VAIO Zの開発者を直撃 新しい価値を提案する“歴代最強Z”のヒミツに迫る 1. 週アスPLUS](http://weekly.ascii.jp/elem/000/000/306/306597/)
2. [これ、本気で描けますよ：液晶ペンタブ業界に嵐を巻き起こす!?――「VAIO Z Canvas」を漫画家が速攻レビュー (1/5) 1. ITmedia PC USER](http://www.itmedia.co.jp/pcuser/articles/1502/17/news056.html)
3. [New XPS 13 | Dell](http://www.dell.com/us/business/p/xps-13-9343-laptop/pd)
4. [ソニー、“音質にこだわった”microSDカード ～技術面と品質管理からアプローチ 1. PC Watch](http://pc.watch.impress.co.jp/docs/news/20150219_688476.html)
# 今週のまとめ (5分)
# 次週予告・告知

(mazzo) 今週もbackspace.fmをお聞きいただき、ありがとうございました。

(drikin) 次回のbackspace.fm #086は、XXXXXゲスト未定

(all) また来週お楽しみに！

**Comment by mazzo-p** [comment]
- [もう、ささらだけではない――「調教いらず」のCeVIOに“新人”歌手がJOYSOUNDから　おっさん・熟女の「演歌歌手」も - ITmedia News](http://www.itmedia.co.jp/news/articles/1502/19/news133.html)
- [【イベントレポート】ITmedia読者感謝祭の参加レポートまとめ。当日聴いた話、会場の雰囲気など - そうすけブログ]{http://sosukeblog.com/2015/02/22/8765/)
- [液晶ペンタブ業界に嵐を巻き起こす!?――「VAIO Z Canvas」を漫画家が速攻レビュー - ITmedia PC USER](http://www.itmedia.co.jp/pcuser/articles/1502/17/news056.html)
