### ISSUE TITLE
バンクーバーで奮闘中の若手UxデザイナーElle Kasaiさんと語る今Podcastに注目している理由

### ISSUE THREAD

**Issue by drikin** [drikin/backspace#81]
今週の公開生放送は日本時間2月29日(日曜)午後2時頃からの収録を予定しています。生放送の閲覧は下記のURLからご覧頂けます。

http://backspace.fm/live.html
# ごあいさつ

こんにちは、backspace.fm 第86回です。
(87回分も録音)
backspace.fmは一週間分のテック系ニュースをお届けするPodcastです。
## 今週の一言

@mazzo: 

@drikin:
公約(?)通りlumia635ゲット

@kai4den:
## 今回のbackspace.fmについて

(mazzo) 今回のbackspace.fmは、現在バンクーバーで奮闘中の若手Uxデザイナーで、最近、Podcastも始められた、かさいエリー さんをゲストに、エリーさんの活動や、異国での日々についてお聞きできればと思っています。

(mazzo) では、エリーさん、簡単に自己紹介をお願いします！

<ここでエリーさん自己紹介>
## 番組フィードバックと配信スケジュールについて

(drikin) 番組に対するフィードバックは#backspacefmにてお願いします！ http://backspace.fm/live.html から視聴頂くと、ページ内のTwitterリストからハッシュタグ付きツイートが簡単にできます！番組中のリアルタイムフィードバックもお待ちしていますのでフィードバックよろしくお願いします。

また生放送スケジュールはGoogleカレンダーにて日程を公開しています。生放送を聞きたい方はぜひカレンダーを登録してください。

https://www.google.com/calendar/embed?src=je3ul6a9tp9esq6efrouf1ht6c%40group.calendar.google.com&ctz=Japan/Tokyo
# 今週のスペシャル (30分)
### 質問集
- 改めてエリーさんの自己紹介
  - 日本での活動
  - 最近の活動
- elle-heightについて
- なぜバンクーバーなのか？サンフランシスコとかは？
  - 日本とバンクーバーの違い、Uxやデザイン的に
- なぜUxを勉強しているのか？
  - Uxの重要性
  - 日本におけるUxの現状
- バンクーバーの魅力、オススメのスポット
- 今どきのデザイナーのエンジニアの線引きってどこにあるんだろう？
- なぜポッドキャストを始めたのか？
- 一人トークの良さ、大変さ
- ポッドキャストにおけるこだわりとか目標
- エリーさんが最近気になってるサービスとかプロダクト
- そのほかのより一般的な最近ハマってること、マイブーム的なもの
### 関連リンク
- [elle-height](http://elle-height.ellekasai.com/)
- [Frog - バンクーバーを拠点とするクリエイター留学サポート企業](http://frogagent.com/)
# 今週のニュース (30分)
1. [Duet Display - Ex-Apple Engineers Turn Your iPad into a Second Display for your Mac](http://www.duetdisplay.com/)
2. [旅の革命──スーツケースもスマートになる « WIRED.jp](http://cms2x.wired.jp/2015/02/22/smart-suitcase/)
3. [Googleの実世界陣取りゲーム Ingress が Android Wear 対応へ。時計からハックも - Engadget Japanese](http://japanese.engadget.com/2015/02/27/google-ingress-android-wear/?ncid=rss_truncated)
4. [【買い物山脈】ライター後藤弘茂がIngressにはまったワケ(上) - PC Watch](http://m.pc.watch.impress.co.jp/docs/column/kaimono/20150224_689692.html)
5. [本日発売『ドラゴンクエストヒーローズ』完成披露発表会。松坂桃李＆桐谷美玲が『DQ』愛を熱く語る！](http://www.i-mezzo.net/log/2015/02/26080539.html)
# 今週のガジェット (30分)
1. 
   [【モバイラーが憧れた名機を今風に蘇らせる】東芝「Libretto 30/60」 ～Windowsモバイルのエポックメイカー - PC Watch](http://m.pc.watch.impress.co.jp/docs/column/mobiler/20150228_690542.html)
2. [腕時計型端末発売1カ月前、アップル来月9日にイベント（ロイター） - Yahoo!ニュース](http://headlines.yahoo.co.jp/hl?a=20150227-00000015-reut-bus_all)
3. [There are 60,000 people testing Windows 10 for phones](http://www.neowin.net/news/there-are-only-60000-people-testing-windows-10-for-phones)
# 今週のまとめ (5分)
# 次週予告・告知

(mazzo) 今週もbackspace.fmをお聞きいただき、ありがとうございました。

(drikin) 次回のbackspace.fm #086は、先日行われたITメディアバーチャルエキスポとbackspace.fmのコラボレーション企画第二段階の公開収録した内容をあらためてアーカイブにて配信する予定です。

ハルロック好きなひと、きゅんくんファン、最新義手の世界まで、もの作りが気になっている人は必聴の内容ですので、お楽しみに！

87回分）
次回のbackspace.fmは、先日スケジュールが合わなくて延期になっていた、日本人で最初にTwitter本社にて採用されたエンジニア、にわさんをゲストに迎えてお届けする予定です。今度こそ、濃いエンジニアトークに期待してください！

(all) また来週お楽しみに！

**Comment by mazzo-p** [comment]
- [モバイラーが憧れた名機を今風に蘇らせる 第4回 東芝「Libretto 30/60」～Windowsモバイルのエポックメイカー - PC Watch](http://pc.watch.impress.co.jp/docs/column/mobiler/20150228_690542.html)
